services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/task/app     # hot reload do código
      - ./data:/var/task/data   # storage local (mock S3)
    env_file:
      - .env
    environment:
      MOCK_AUTH: "true"
      MOCK_BOOKSTACK: "true"
      MOCK_S3: "true"
